[package]
edition = "2018"
name = "juniper_codegen_tests"
publish = false
version = "0.1.0"

[dependencies]
futures = "0.3.1"
juniper = {path = "../../juniper"}

[dev-dependencies]
serde_json = {version = "1"}
tokio = {version = "1.1", features = ["rt-core", "time", "macros"]}
trybuild = "1.0.25"
