[package]
authors = ["Christoph Herzog <chris@theduke.at>"]
edition = "2018"
name = "async_await"
publish = false
version = "0.1.0"

[dependencies]
futures = "0.3.1"
juniper = {path = "../../juniper"}
tokio = {version = "1.1", features = ["rt-core", "time", "macros"]}
